#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

const envDir = path.join(__dirname, '..', 'src', 'environments');
const envFile = path.join(envDir, 'environment.ts');

const supabaseUrl = process.env['NG_APP_SUPABASE_URL'] || '';
const supabaseKey = process.env['NG_APP_SUPABASE_KEY'] || '';
const bankId = process.env['NG_APP_BANK_ID'] || 'TPB';
const bankAccountNo = process.env['NG_APP_BANK_ACCOUNT_NO'] || '';
const bankAccountName = process.env['NG_APP_BANK_ACCOUNT_NAME'] || '';

if (!supabaseUrl || !supabaseKey) {
  console.warn('⚠️  WARNING: NG_APP_SUPABASE_URL or NG_APP_SUPABASE_KEY is not set!');
}

const content = `// Auto-generated by scripts/generate-env.js — DO NOT EDIT MANUALLY
export const environment = {
  production: true,
  supabaseUrl: '${supabaseUrl}',
  supabaseKey: '${supabaseKey}',
  bankId: '${bankId}',
  bankAccountNo: '${bankAccountNo}',
  bankAccountName: '${bankAccountName}'
};
`;

if (!fs.existsSync(envDir)) {
  fs.mkdirSync(envDir, { recursive: true });
}

fs.writeFileSync(envFile, content, 'utf8');
console.log('✅ Generated src/environments/environment.ts from environment variables');
